"""Tips and gotchas for working with Access via MCP."""

_TIPS: dict[str, str] = {
    "eval": (
        "ac_eval_vba can query the Access Object Model without new tools:\n"
        "  Application.IsCompiled — check if VBA is compiled (no compile triggered)\n"
        "  SysCmd(10, 2, \"formName\") — check if form is open (acSysCmdGetObjectState=10, acForm=2)\n"
        "    Returns: 0=closed, 1=open, 2=new, 4=dirty, 8=has new record\n"
        "  Application.BrokenReference — True if any VBA reference is broken\n"
        "  Screen.ActiveForm.Name / Screen.ActiveControl.Name — active form/control\n"
        "  Forms.Count — number of open forms\n"
        "  TempVars(\"x\") — session-persistent variables (read/write across tools)\n"
        "  DLookup/DCount/DSum — domain aggregate functions\n"
        "  TypeName(expr) — inspect type of any expression\n"
        "  Eval only works for expressions/functions, NOT statements/Subs."
    ),
    "controls": (
        "FormatConditions: access_list_controls / access_get_control show\n"
        "  'format_conditions' count when a control has conditional formatting.\n"
        "  ConditionalFormat data in SaveAsText is binary (hex blobs, not readable).\n"
        "  To read details: use VBA via access_run_vba (FormatConditions collection in Design view).\n"
        "  To modify: write a temp VBA function with access_vbe_append, call with access_run_vba.\n"
        "  BE CAREFUL: modifying control properties may break existing conditional formatting.\n\n"
        "Control types for access_create_control:\n"
        "  119 = acCustomControl (ActiveX) — use class_name param for ProgID (e.g. 'Shell.Explorer.2')\n"
        "  128 = acWebBrowser (native, NOT ActiveX — no OLE needed)\n"
        "  Common: 100=Label, 101=Rectangle, 103=Image, 104=CommandButton,\n"
        "          106=CheckBox, 107=OptionGroup, 109=TextBox, 110=ListBox,\n"
        "          111=ComboBox, 112=Subform, 118=Page, 123=Tab (TabControl)\n\n"
        "Tab controls:\n"
        "  CreateControl makes a TabControl WITH two pages already on it.\n"
        "  To place a control on a page, pass parent with the PAGE name\n"
        "    (e.g. 'Page1'), NOT the tab control name. Without parent the control\n"
        "    lands on the section and shows on every page. Since v0.7.59\n"
        "    access_create_control returns a 'warning' when the new control\n"
        "    falls inside a tab control and parent was empty.\n"
        "  access_list_controls lists the tab control itself (123) and every\n"
        "    Page carries parent=<tab control name>."
    ),
    "gotchas": (
        "COM & ODBC:\n"
        "  dbSeeChanges (512) — REQUIRED in CurrentDb.Execute for DELETE/UPDATE on ODBC linked tables\n"
        "  LIKE wildcards — use % for ODBC (not *)\n"
        "  COM from threads — MUST call pythoncom.CoInitialize() before and CoUninitialize() in finally\n"
        "  COM apartment threading — can't access COM objects from Timer threads (capture hwnd as int first)\n"
        "  ListBox.Value — use .Column(0) explicitly, .Value may return wrong column\n"
        "  ComboBox filtering — never use Change event (infinite loops), use TextBox + LostFocus\n"
        "  dbAttachSavePWD = 131072 (NOT 65536) — use DoCmd.TransferDatabase, not DAO Attributes\n"
        "  Multiple JOINs — Access requires nested parentheses: FROM (A JOIN B ON ...) JOIN C ON ...\n\n"
        "VBA:\n"
        "  Str() adds leading space to positive numbers — use CStr() instead\n"
        "  Chr(128) truncates MsgBox text — use ChrW(8364) or \"EUR\" for euro symbol\n"
        "  ListBox AddItem — column separator is \";\", never use Format \"#,##0.00\" (comma breaks columns)\n"
        "  GetClipboardFilePath() can throw — always wrap in On Error Resume Next\n\n"
        "Startup:\n"
        "  SHIFT bypass is ON by default — OpenCurrentDatabase and /decompile hold SHIFT to skip AutoExec/startup forms.\n"
        "    The key-down is global: it shifts whatever the user types anywhere on the machine while held (~0.3s per open, ~3s per decompile).\n"
        "    Set MCP_ACCESS_SHIFT_BYPASS=0 in the server env to turn it off once the databases guard their own startup:\n"
        "    `If Not Application.UserControl Then Exit Function` opts a database out under COM automation and needs no bypass at all.\n"
        "  Any auto-opened forms are closed automatically after opening the database."
    ),
    "sql": (
        "Jet SQL DDL (access_execute_sql):\n"
        "  YESNO is not valid — use BIT, or better use access_create_table (accepts 'yesno')\n"
        "  DEFAULT not supported in CREATE TABLE — use access_set_field_property or access_create_table\n"
        "  AUTOINCREMENT works as a type (no IDENTITY needed)\n"
        "  Use SHORT instead of SMALLINT, LONG instead of INT\n"
        "  Prefer access_create_table over CREATE TABLE SQL for full type+default+description support\n\n"
        "ODBC pass-through:\n"
        "  QueryDef.Connect limit 255 chars — hardcode a minimal connect string:\n"
        "  \"ODBC;DRIVER={ODBC Driver 17 for SQL Server};SERVER=myserver\\sqlexpress;"
        "DATABASE=mydb;UID=myuser;PWD=mypassword\""
    ),
    "vbe": (
        "VBE line numbers are 1-based.\n"
        "ProcCountLines can inflate the last proc's count past end of module — always clamp.\n"
        "Access must be Visible=True for VBE COM access to work.\n"
        "'Trust access to the VBA project object model' must be enabled in Trust Center.\n"
        "After design operations (set_control_props, create_control, delete_control),\n"
        "  close the form in Design view before accessing VBE CodeModule.\n"
        "access_vbe_append: was encoding & as &amp; (fixed in v0.7.3 with html.unescape).\n\n"
        "Reading VBA code:\n"
        "  For specific procedures: use access_vbe_get_proc (fast, precise).\n"
        "  For procedure index: use access_vbe_module_info first.\n"
        "  access_get_code exports the ENTIRE form (controls + VBA, can be 90KB+) — avoid for VBA investigation.\n"
        "  Recommended flow: access_vbe_module_info → access_vbe_get_proc for each relevant proc.\n\n"
        "start_line vs body_line (get_proc / module_info):\n"
        "  start_line = VBE proc start — INCLUDES the blank separator + comment lines above the proc.\n"
        "  body_line  = the Sub/Function/Property declaration line itself.\n"
        "  Use start_line for whole-proc operations; body_line for body line-range edits.\n\n"
        "Editing procedures:\n"
        "  access_vbe_replace_proc replaces a whole proc by name and PRESERVES the blank\n"
        "    separator line above it (no more manual re-add after each replace).\n"
        "  Delete a proc: access_vbe_replace_proc(..., new_code='') — also removes its leading blank separator.\n"
        "  access_vbe_replace_lines: pass new_code (string) OR new_lines (list of lines; '' = blank line).\n"
        "    A replace that deletes lines but inserts nothing (empty new_code/new_lines) is flagged in the result.\n\n"
        "access_vbe_patch_proc flags (v0.7.52):\n"
        "  atomic (DEFAULT TRUE) — if ANY patch fails to match, NOTHING is written and the\n"
        "    module is byte-for-byte unchanged. On an ABORTED result, re-read the code and\n"
        "    re-send the ENTIRE batch: the patches that DID match were discarded too, so\n"
        "    re-sending only the failed ones silently drops the rest. atomic=false restores\n"
        "    the old best-effort behaviour (partial writes).\n"
        "  match_case (DEFAULT FALSE) — VBA is case-insensitive and the VBE rewrites casing\n"
        "    on its own, so anchors match regardless of case. The note in the result echoes\n"
        "    the text as actually stored. Set match_case=true to demand an exact-case match.\n"
        "  require_unique — refuse to patch when the anchor matches more than once; the\n"
        "    result reports how many times and at which module lines.\n\n"
        "Patching the (Declarations) section:\n"
        "  access_vbe_module_info returns declarations: {start_line: 1, count: N}.\n"
        "  access_vbe_get_proc(proc_name='(Declarations)')   — read it.\n"
        "  access_vbe_patch_proc(proc_name='(Declarations)')  — patch it (Option lines are\n"
        "    never stripped there, unlike inside a proc).\n"
        "  access_vbe_replace_proc REFUSES '(Declarations)' — new_code='' would wipe\n"
        "    Option Explicit and every module-level Const in one unconfirmed call.\n"
        "  If count == 0 the module has no declarations section; create one with\n"
        "    access_vbe_replace_lines(start_line=1, count=0, new_code=...).\n\n"
        "Writing code can change modules you never touched:\n"
        "  The VBA editor keeps ONE canonical spelling per identifier across the\n"
        "  whole project. Declare Dim Url As String in a new module and the VBE\n"
        "  rewrites every existing url to Url — in every other module, silently.\n"
        "  VBA is case-insensitive so nothing breaks at runtime, but if the VBA is\n"
        "  exported to text and versioned, a twenty-line change turns into a diff\n"
        "  across files nobody opened. It is Office behaviour, not this server.\n"
        "  Pick the casing an identifier already has in the project and the noise\n"
        "  disappears; access_vbe_find tells you which spelling is in use.\n\n"
        "total_lines is cm.CountOfLines (v0.7.52) — a trailing blank line is a real,\n"
        "  addressable line, so module_info/get_lines and patch_proc no longer disagree by 1."
    ),
    "compile": (
        "Checking VBA after an edit — prefer access_vbe_check_syntax:\n"
        "  It validates the ALREADY OPEN project: no decompile, no RunCommand, no Design\n"
        "  view, no second Access instance, nothing discarded. Catches unbalanced\n"
        "  If/For/Do/While/Select/With/Type/Enum blocks, code outside a procedure and\n"
        "  misplaced Option statements. Scope it with object_type/object_name or check all.\n"
        "  It is NOT a compiler: ok=true does NOT prove the project compiles — it does not\n"
        "  resolve identifiers, types or references. Read modules_checked and skipped: a\n"
        "  module that could not be read is reported, never counted as clean.\n\n"
        "access_compile_vba tips (real compile — DESTRUCTIVE SETUP):\n"
        "  WARNING: it decompiles first (MSACCESS.EXE /decompile subprocess) and then quits\n"
        "  or closes the database, which discards UNSAVED VBA. Do not use it as a quick\n"
        "  post-edit check — use access_vbe_check_syntax for that.\n"
        "  Use timeout param — RunCommand(126) shows MsgBox on error, blocks without it.\n"
        "  With timeout: polls every 2s, auto-clicks End/OK button + reports module/line/code via VBE.ActiveCodePane.\n"
        "  Also captures screenshot of the error MsgBox (dialog_screenshot in response).\n"
        "  Before compiling, check: Eval('Application.BrokenReference') — broken refs cause mysterious failures.\n"
        "  After compile error: use access_vbe_get_lines to read the problematic code, fix with access_vbe_replace_lines."
    ),
    "design_vbe": (
        "Design view + VBE conflict:\n"
        "  After design operations, the form may remain open in Design view.\n"
        "  access_vbe_replace_proc closes the form (acSaveYes) before accessing VBE.\n"
        "  All design operations invalidate the cache pair (_parsed_controls_cache, _cm_cache).\n\n"
        "SaveAsText encoding:\n"
        "  Modules (.bas) — cp1252 (ANSI, no BOM)\n"
        "  Forms/reports/queries/macros — utf-16 (UTF-16LE with BOM)\n"
        "  access_set_code handles this automatically.\n\n"
        "Injecting code rewrites the form design-window geometry:\n"
        "  After writing VBA into a form (access_set_code with VBA-only text, or any\n"
        "  access_vbe_* writer), the NEXT text export of that form shows different\n"
        "  Left/Top/Right/Bottom on the Begin Form block, plus Checksum and a few\n"
        "  internal hex blocks. That is the DESIGN WINDOW position and size, not the\n"
        "  layout. No control moved. If a diff touches only those form-level values\n"
        "  and no control has its own Left/Top changed, nothing moved — the commit is\n"
        "  safe to accept without opening Access."
    ),
    "macros": (
        "Working with Access macro objects:\n"
        "  Macros are first-class — no dedicated tool, they reuse the regular code/object tools.\n"
        "  List:    access_list_objects(object_type='macro')\n"
        "  Read:    access_get_code(object_type='macro', name='myMacro') → SaveAsText UTF-16 text\n"
        "  Write:   access_set_code(object_type='macro', name='myMacro', code=...) — writes utf-16 encoded\n"
        "           If 'myMacro' exists it is overwritten; otherwise created.\n"
        "  Run:     access_run_macro(macro_name='myMacro')\n"
        "  Delete:  access_delete_object(object_type='macro', object_name='myMacro', confirm=true)\n\n"
        "Typical edit workflow:\n"
        "  1. text = access_get_code('macro', 'myMacro')\n"
        "  2. modify the text (e.g. swap a RunCommand value, add an Action)\n"
        "  3. access_set_code('macro', 'myMacro', new_text)\n\n"
        "Notes:\n"
        "  - The SaveAsText format for macros is a structured Action / SubMacro / Argument tree.\n"
        "    Hand-editing is feasible but easy to corrupt — start from a SaveAsText export.\n"
        "  - Binary section handling (PrtMip / PrtDevMode) does NOT apply to macros — they have none.\n"
        "  - Data macros attached to tables (BeforeChange/AfterUpdate triggers) are NOT exposed here;\n"
        "    use access_execute_sql with DDL or open the table in design view manually."
    ),
    "lint": (
        "access_lint_form — deterministic UI design validation (no LLM, no guesswork):\n"
        "  Rules: contrast (WCAG 2.1), overlap, out_of_bounds, truncation,\n"
        "         sibling_inconsistency, misalignment, invisible_or_zero_size.\n"
        "  summary.verdict: PASS (clean) / REVIEW (warnings) / FAIL (>=1 error).\n"
        "  Static — one SaveAsText export, never opens Design view.\n\n"
        "Thresholds:\n"
        "  contrast — WCAG ratio < 4.5:1 normal text (3:1 for >=18pt or >=14pt bold).\n"
        "    Skips transparent (BackStyle=0 resolved to section/form bg) and theme/system\n"
        "    colours (high bit 0x80000000, e.g. -2147483633) which can't be checked statically.\n"
        "  overlap — sibling rectangles intersecting >4 twips in the same section+parent.\n"
        "    Cross-TabPage controls and attached labels never count (parser ignores them).\n"
        "  out_of_bounds — right edge > form Width, or bottom > section Height (CanGrow-aware).\n"
        "  truncation — caption wider than the control. measure='auto'|'wizhook'|'heuristic'.\n"
        "    WizHook needs a COMPILED VBA project (Application.IsCompiled); else heuristic.\n\n"
        "Design-quality rules (info only — never change the verdict, never reach\n"
        "  the embedded compact lint): grid_alignment (off the 60-twip grid),\n"
        "  spacing_consistency (uneven column gaps), edge_margin (control hugging\n"
        "  the form edge), hierarchy (action/title text not larger than body),\n"
        "  generic_font (Arial/Roboto/Inter/Times New Roman/MS Sans Serif).\n"
        "  A form built with access_build_form (esp. a design direction) passes\n"
        "  all of them clean. See access_tips('design').\n\n"
        "Enforcement:\n"
        "  access_set_control_props / access_set_multiple_controls / access_create_control\n"
        "  attach a compact 'lint' block (errors+warnings) to their result automatically.\n"
        "  Treat verdict=FAIL as blocking: fix every error, then re-check, before finishing.\n"
        "  Pass skip_lint=true only for bulk programmatic edits.\n\n"
        "Colours: Access stores ForeColor/BackColor as BGR Long (b*65536+g*256+r).\n"
        "  16777215=white, 0=black, 255=red, 16711680=blue."
    ),
    "layout": (
        "Designing good Access forms — let the MCP do the twip arithmetic.\n\n"
        "BEST: use access_build_form. Describe the form declaratively (title,\n"
        "  ordered fields, action buttons, single|two-column) and it computes every\n"
        "  Left/Top/Width/Height from the canonical grid, applies a closed palette,\n"
        "  sets a sane tab order and sizes the form/sections. The model never picks\n"
        "  a coordinate. Example:\n"
        "    access_build_form(db, 'frmCliente', record_source='tblCliente',\n"
        "        title='Ficha de cliente',\n"
        "        fields=['Nombre', {'field':'Provincia','control':'combobox'},\n"
        "                {'field':'Notas','control':'memo'}],\n"
        "        actions=[{'caption':'Guardar','on_click':'[Event Procedure]'},\n"
        "                 {'caption':'Cerrar'}])\n\n"
        "When placing controls by hand (access_create_control / set_control_props),\n"
        "  pass snap_to_grid=true and follow these canonical numbers (twips; the\n"
        "  Access native grid is 60/twip — 24 dots per inch, 1440 twips = 1 inch):\n"
        "    GRID 60 | MARGIN 240 | label width 1800 | field width 2400\n"
        "    label→field gap 120 | row height 300 | row gap 120 (stride 420)\n"
        "    memo height 960 | button 1500x360, gap 120 | header 720 | footer 600\n"
        "  Columnar recipe: x_label=240, x_field=2160; row i top = 240 + i*420.\n"
        "  Single-column form width = 240 + 1800 + 120 + 2400 + 240 = 4800.\n\n"
        "Palette (BGR Long): form_bg=16119285 (#F5F5F5), field_bg=16777215 (white),\n"
        "  field_border=13421772 (#CCCCCC), text=3355443 (#333333),\n"
        "  accent=15426341 (#2563EB, available for highlights).\n"
        "  Pick FROM this list instead of inventing colours — these pass WCAG contrast.\n"
        "  Note: the form-header band is themed by Access (a literal BackColor doesn't\n"
        "  stick), so the title is dark text, not white-on-accent.\n\n"
        "Typography: Calibri; labels 10pt, fields 11pt, title 16pt bold (dark).\n"
        "For a styled look beyond the default, pass theme=despacho|panel|archivo —\n"
        "  curated design directions (see access_tips('design')).\n"
        "Verify the result with access_lint_form (and access_screenshot for a look)."
    ),
    "design": (
        "Designing a form with REAL taste — within what native Access can render.\n\n"
        "USE access_build_form with a curated design DIRECTION (theme=). Each one\n"
        "  is a coherent bundle: a typeface with character, an intentional type\n"
        "  scale (1.2-1.25 modular), a dominant+accent palette with VERIFIED WCAG\n"
        "  contrast, a spacing rhythm/density, and an accent header band. They pass\n"
        "  the lint clean by construction.\n\n"
        "  despacho — character. Serif title (Constantia) on warm paper #FBFAF7,\n"
        "    Segoe UI body, teal accent band #0F766E (white title 5.47:1). No card,\n"
        "    comfortable spacing. For a classic, editorial ficha.\n"
        "  panel — sober office. Segoe UI Semibold title, white card on a cool\n"
        "    canvas #F1F5F9, slate band #1E293B. Comfortable. For data-entry apps.\n"
        "  archivo — warm editorial. Serif title (Cambria), Corbel body, paper\n"
        "    #F4F1EC, clay band #7C4A33 (white 7.28:1). No card, spacious. Roomy.\n\n"
        "  Example:\n"
        "    access_build_form(db, 'frmCliente', record_source='tblCliente',\n"
        "        title='Ficha de cliente',\n"
        "        fields=['Nombre', {'field':'Provincia','control':'combobox'},\n"
        "                {'field':'Notas','control':'memo'}],\n"
        "        actions=[{'caption':'Guardar cambios','on_click':'[Event Procedure]'},\n"
        "                 'Cerrar'],\n"
        "        theme='despacho')\n\n"
        "PRINCIPLES (these are what carry a flat UI):\n"
        "  - Typeface with character — NOT Arial/Roboto/Inter/Times New Roman (the\n"
        "    generic_font lint flags those). Pair a display title with a clean body.\n"
        "  - Cohesive palette — one dominant surface + one accent, not a rainbow.\n"
        "    Verify every text/background pair passes WCAG (the contrast lint does).\n"
        "  - Hierarchy — title clearly larger than body (the type scale guarantees\n"
        "    it); actions read at least as large as the body (hierarchy lint).\n"
        "  - Rhythm & containment — consistent spacing, a header band, an optional\n"
        "    card; let the content breathe (density), don't fill every twip.\n"
        "  - Copy in the active voice: 'Guardar cambios', not 'Botón1'.\n\n"
        "HONEST CEILING — native Access has NO gradients, shadows, rounded corners,\n"
        "  blur/transparency, hover/animation, or fine letter/line-spacing. Don't\n"
        "  promise web-grade polish; aim for coherent and tasteful within the flat\n"
        "  medium. A direction is a real step up from the ad-hoc default, not a CSS\n"
        "  design system.\n\n"
        "Always verify: access_lint_form (verdict PASS, and no generic_font /\n"
        "  hierarchy info) + access_screenshot for the actual look."
    ),
    "subform_tabcontrol": (
        "SubForm inside TabControl Page — BROKEN LAYOUT workaround:\n"
        "  Access recalculates TabControl positions when a SubForm exists inside a Page,\n"
        "  even with no SourceObject, both via CreateControl and LoadFromText.\n"
        "  Opening in Design view also triggers recalculation.\n\n"
        "SOLUTION: SubForm as SIBLING of TabControl (not child of Page).\n"
        "  1. access_export_text the form\n"
        "  2. In the UTF-16 text, add an EMPTY Page inside the TabControl\n"
        "  3. Add SubForm OUTSIDE the TabControl (same indent level, sibling in Detail section)\n"
        "     Set Visible = NotDefault (hidden by default)\n"
        "     Position it at the same coords as the Page content area (Left=75, Top=465)\n"
        "  4. Add OnChange =\"[Event Procedure]\" to the TabControl (Begin Tab)\n"
        "  5. Add OnOpen =\"[Event Procedure]\" to the form properties\n"
        "  6. Add CodeBehindForm section at end with VBA:\n"
        "     Private Sub Form_Open(Cancel As Integer)\n"
        "         sfName.Visible = False\n"
        "     End Sub\n"
        "     Private Sub tabName_Change()\n"
        "         If tabName.Pages(tabName.Value).Name = \"pagX\" Then\n"
        "             If sfName.SourceObject = \"\" Then\n"
        "                 sfName.SourceObject = \"Form.subf_xxx\"\n"
        "             End If\n"
        "             sfName.Visible = True\n"
        "         Else\n"
        "             sfName.Visible = False\n"
        "         End If\n"
        "     End Sub\n"
        "  7. access_import_text — single operation, NEVER open Design view after\n\n"
        "CRITICAL: Do NOT use set_form_property, set_control_props, or vbe_append\n"
        "  after import — they open Design view which recalculates positions.\n"
        "  All changes must go in the text file BEFORE import."
    ),
}


def ac_tips(topic: str = "") -> dict:
    """Return tips and gotchas for working with Access via MCP."""
    if not topic:
        return {
            "available_topics": list(_TIPS.keys()),
            "usage": "Call access_tips with a topic to get relevant tips.",
        }
    key = topic.lower().strip()
    if key in _TIPS:
        return {"topic": key, "tips": _TIPS[key]}
    # Fuzzy match — return any topic containing the search term
    matches = {k: v for k, v in _TIPS.items() if key in k or key in v.lower()}
    if matches:
        return {"matched_topics": {k: v for k, v in matches.items()}}
    return {
        "error": f"Topic '{topic}' not found.",
        "available_topics": list(_TIPS.keys()),
    }
